import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import '@/styles/utils/variables.css'
import '@app-styles/utils/mixins.css'
import NavBar from '@/components/layout/nav-bar/nav-bar'
import styles from '@/app/page.module.css'
import { PodcastsContextProvider } from '@/contexts/podcast-context/podcasts.context'
import { Suspense } from 'react'
import Loading from './loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mainLayout">
          <div className="flex-grow">
            <Suspense fallback={<Loading />}>
              <NavBar />
              <main className={styles.main}>
                <PodcastsContextProvider>{children}</PodcastsContextProvider>
              </main>
            </Suspense>
          </div>
        </div>
      </body>
    </html>
  )
}
