name: Lint

on:
  push:
    branches:
      - '**' # Execute on all branches every time there is a push
  pull_request:
    branches:
      - '**' # Execute on all branche every time there is a pull request
  workflow_dispatch: # Allow manual execution

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache -t my-eslint .

      - name: Run ESLint
        run: docker run my-eslint
