name: Test

on:
  push:
    branches:
      - '**' # Execute on all branches every time there is a push
  pull_request:
    branches:
      - '**' # Execute on all branche every time there is a pull request
  workflow_dispatch: # Allow manual execution

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
